uploads = []
generated = []

[[outputs]]
id = "eaJXKYfNM6IKwkJtDzJzO"
uri = "file://index_html.zip"
type = "unspecified"
title = "index.html"

[[outputs]]
id = "VL46MWujN_GyqTr-5usDI"
uri = "file://buba-website.zip"
type = "unspecified"
title = "BUBA Website — Open Locally"

[[outputs]]
id = "1ic_UUQ7jfbyTN13BC1Hu"
uri = "file://buba-cloudflare.zip"
type = "unspecified"
title = "BUBA Token — Cloudflare (self-contained)"

[[outputs]]
id = "0NGtYikpxJufqR0ybmcYM"
uri = "file://buba-flat.zip"
type = "unspecified"
title = "BUBA — All Files Flat (Fixed)"

[[outputs]]
id = "vdcWgAmqYQkGgameaL0rz"
uri = "file://buba-single.zip"
type = "unspecified"
title = "BUBA — Single index.html (all in one)"

[[outputs]]
id = "Il_bdrF39T0no5Gnwk4o6"
uri = "file://buba-deploy.zip"
type = "unspecified"
title = "BUBA — Ready to Deploy"
